# Generated by Django 3.0.5 on 2020-04-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20200428_1309'),
        ('accounts', '0002_auto_20200420_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(to='stores.Tag'),
        ),
    ]
