# Generated by Django 3.0.5 on 2020-04-28 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20200428_1309'),
        ('accounts', '0003_user_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.Tag')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'accounts_user_tag',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='tags',
            field=models.ManyToManyField(through='accounts.UserTag', to='stores.Tag'),
        ),
    ]
