# Generated by Django 3.0.5 on 2020-04-28 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200428_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(0, 'Female'), (1, 'Male')]),
        ),
        migrations.AlterModelTable(
            name='usertag',
            table='accounts_user_tags',
        ),
    ]
