# Generated by Django 2.2.7 on 2020-04-08 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='menu_name',
            new_name='name',
        ),
    ]
