# Generated by Django 3.0.5 on 2020-04-09 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='store',
        ),
    ]
