# Generated by Django 3.0.5 on 2020-04-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='bhour_list',
            new_name='bhour',
        ),
        migrations.AlterField(
            model_name='store',
            name='tags',
            field=models.ManyToManyField(blank=True, to='stores.Tag'),
        ),
    ]
