# Generated by Django 3.0.5 on 2020-04-22 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_store_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='bhour',
            new_name='bhour_list',
        ),
    ]
