# Generated by Django 3.0.5 on 2020-04-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20200422_1739'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='bhour_list',
        ),
        migrations.AddField(
            model_name='store',
            name='bhour',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='stores.Store'),
        ),
        migrations.AlterField(
            model_name='review',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='stores.Store'),
        ),
        migrations.AlterField(
            model_name='store',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='latitude',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='longitude',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='tags',
            field=models.ManyToManyField(to='stores.Tag'),
        ),
    ]
