# Generated by Django 3.0.5 on 2020-04-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='menus',
        ),
        migrations.AddField(
            model_name='store',
            name='menus',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
