# Generated by Django 3.0.5 on 2020-04-20 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stores', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(choices=[('0', 'Breakfast'), ('1', 'Lunch'), ('2', 'Dinner'), ('3', 'Snack')], default=False, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('menus', models.CharField(max_length=300)),
                ('party', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('score', models.FloatField(max_length=10)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='stores.Store')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
