# Generated by Django 3.0.5 on 2020-04-22 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200420_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='writer',
            new_name='user',
        ),
    ]
