# Generated by Django 3.0.5 on 2020-04-30 22:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20200429_1353'),
        ('posts', '0003_auto_20200422_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stores.Store'),
        ),
    ]
